apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-finder-deploy
  namespace: default
  labels:
    app: devfinder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devfinder
  template:
    metadata:
      labels:
        app: devfinder
    spec:
      containers:
      - name: devfinder-image
        image: roxsross12/dev-finder:1.0.1
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: dev-finder-svc
  namespace: default
  labels:
    app: devfinder
spec:
  selector:
    app: devfinder
  ports:
  - port: 80
    targetPort: 80
  type: NodePort        